#!/usr/bin/env python3
"""One-shot: wait out Instagram's IP rate limit, then fetch @intl_chadwick
posts via the feed endpoint (single gentle request per cycle) and merge them
into assets/media.js. Exits 0 on success, 1 if every cycle stayed limited."""
import json, os, subprocess, sys, time

BASE = os.path.dirname(os.path.abspath(__file__))
UID = "60923618020"  # @intl_chadwick
CYCLES = 5
WAIT_S = 2400  # 40 min between attempts


def fetch_posts():
    from curl_cffi import requests as r
    resp = r.get(f"https://i.instagram.com/api/v1/feed/user/{UID}/?count=12",
                 headers={"x-ig-app-id": "936619743392459"},
                 impersonate="safari", timeout=30)
    if resp.status_code != 200:
        raise RuntimeError(f"HTTP {resp.status_code}")
    items = resp.json().get("items", [])
    posts = []
    os.makedirs(os.path.join(BASE, "assets", "insta"), exist_ok=True)
    for item in items[:6]:
        media = item.get("carousel_media", [item])[0]
        cands = media.get("image_versions2", {}).get("candidates", [])
        if not cands:
            continue
        code = item["code"]
        img = subprocess.run(["curl", "-sfL", "--max-time", "30", cands[0]["url"]],
                             capture_output=True, check=True).stdout
        rel = f"assets/insta/intl_chadwick_{code}.jpg"
        open(os.path.join(BASE, rel), "wb").write(img)
        cap = (item.get("caption") or {}).get("text", "")
        posts.append({"code": code, "img": rel,
                      "video": item.get("media_type") == 2, "caption": cap[:120]})
        print("saved", code, flush=True)
    return posts


def merge(posts):
    path = os.path.join(BASE, "assets", "media.js")
    m = json.loads(open(path).read().split("window.CI_MEDIA = ", 1)[1].rstrip().rstrip(";"))
    m["instagram"]["intl_chadwick"] = {"followers": None, "posts": posts}
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by refresh_media.py — do not edit by hand\nwindow.CI_MEDIA = ")
        json.dump(m, f, ensure_ascii=False, indent=2)
        f.write(";\n")


for cycle in range(1, CYCLES + 1):
    print(f"cycle {cycle}: waiting {WAIT_S}s for rate limit to lift", flush=True)
    time.sleep(WAIT_S)
    try:
        posts = fetch_posts()
        if posts:
            merge(posts)
            print(f"MERGED {len(posts)} intl_chadwick posts", flush=True)
            sys.exit(0)
        print("no renderable posts in response", flush=True)
    except Exception as ex:
        print(f"cycle {cycle} still limited: {ex}", flush=True)
print("gave up after all cycles", flush=True)
sys.exit(1)
